---
- name: setup group
  group: name={{api_group}} system=yes
- name: Setup user
  user: name={{api_user}} system=yes group={{api_group}}

- name: Add in custom apt key
  apkt_key: url=https://region-a.geo-1.objects.hpcloudsvc.com/v1/46995959297574/mini-mon/public_repo/mon.gpg state=present
- name: Add in custom apt repo
  apt_repository: repo='deb https://region-a.geo-1.objects.hpcloudsvc.com/v1/46995959297574/mini-mon/public_repo precise release' state=prsent

- name: Install monasca-api
  apt: name=monasca-api state=latest
  notify:
    - restart monasca-api

- name: create log_dir
  file: path={{monasca_log_dir}} state=directory owner=root group={{api_group}} mode=775

- name: create conf_file from template
  template: dest={{api_conf_file}} owner={{api_user}} group={{api_group}} mode=640 src=api-confi.yml.j2
  notify:
    - restart monasca-api
